### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AndrewDryga** [AndrewDryga/vagrant-box-osx#29]
Here you can leave any ideas how to improve box. Its faster if you suggest a solution, rather than noticing a problem.

Right now for version 0.2.2 the list is:
- [x] Update Max OS (probably to v10.11)
- [x] Increase dynamic disc size to 128 GB
- [x] Update XCode (#38)
- [x] Fix folder owner for `/Library/Caches/Homebrew` (found by `brew doctor`)
  `sudo chown -R vagrant:admin /Library/Caches/Homebrew`
- [x] Update Vagrantfile sample, to show NFS folders usage
- [x] `sudo /usr/sbin/DevToolsSecurity --enable` to avoid errors on GUI password prompts
- [x] Update and enter password for Homebrew Cask (it asks for password when you use it for first time)
- [x] Speed up the machine in sample Vagrantfile: https://github.com/mitchellh/vagrant/issues/2864
- [ ] Find a way to solve mouse pointer issue (from common issues) in a nice way
- [x] Update all package managers
- [x] Update puppet
- [x] Reduce box size `diskutil secureErase freespace 0 Vagrant` and delete all logs (again) and http://vmassuchetto.github.io/2013/08/14/reducing-a-vagrant-box-size/
- [x] Simplify using launchctl with https://github.com/eddiezane/lunchy
- [x] Remove "Recovery HD" to reduce box size
- [ ] Add defines to install additional tools like it did in: https://github.com/radeksimko/vagrant-osx/blob/master/Vagrantfile

**Comment by cybertk** [comment]
I created a 10.11 box, but the box is a little lagging in shell, do you have any idea?

**Comment by cybertk** [comment]
Fixed by using 4 cpus

**Comment by dho825** [comment]
Is there a way to run the iOS simulator/GUI app vis a vis vagrant from the terminal? e.g. x11? Have you ever tried it as seen on this blogpost from [coderwall](https://coderwall.com/p/ozhfva/run-graphical-programs-within-vagrantboxes).

**Comment by WayneBuckhanan** [comment]
@dho825 OSX doesn't use X11 to display the desktop, so you can't set up display forwarding in that manner. The linked article is running things the other way -- OSX host, not OSX guest. 

You can turn on the full OSX GUI, but I'm not aware of any way to open an individual window into the host OS from an OSX guest.

**Comment by DanielThurau** [comment]
I was able to download OS X El Capitan to continue on and update Xcode to 7.1 to support iOS 9 devices.  Password protected update for Xcode.  Box update coming soon? Or can I replace the Developer ID through vagrant file?

**Comment by AndrewDryga** [comment]
@DanielThurau I don't know any ways to change Apple ID via CLI, but you can try to boot VM in GUI mode and login into your account in App Store manually. (Look for "Logout" menu item first.)

I do plan to release new version, but I can't give you any estimates.

**Comment by AndrewDryga** [comment]
The main issue with this boxes is that there are no good place to host it. File is large and it consumes 2 terabytes traffic per month.

**Comment by cybertk** [comment]
Can we host it on Dropbox?

**Comment by AndrewDryga** [comment]
Nope, Dropbox will delete it after few first downloads.

**Comment by cybertk** [comment]
Really? I don't see it in documentation.

**Comment by teocci** [comment]
hey guys if you have problems to run your project on XCode you can also use VMWare using the same Disk create with vagrant.

**Comment by fengshuo211** [comment]
Is this possible to increase the default disk spaces? I found the default disk space isn't enough for me.

**Comment by teocci** [comment]
@fengshuo211m yes you can, just follow the following steps:
- Turn off the OS in the your Virtual Machine
- Shut down VirtualBox again.
- Make a copy of the VDI file – just in case (“vagrant.vdi” -> “vagrantCopy.vdi“)
- Open your terminal or  Windows command prompt
- move to the location of the VDI file that you wish to resize 
```
cd /path/to/your/vm/vagrant.vdi
```
- At the terminal, type:
```
VBoxmanage modifyhd vagrant.vdi --resize 500000
```
this will re-size the drive to 500 GB. Pick a value that suits you. Note, your vdi file will not change in size at this point. The output should look like:
```
VBoxmanage modifyhd vagrant.vdi --resize 500000
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
```

**Comment by fengshuo211** [comment]
@teocci , I found the actual disk file is not a `vdi` file, i'ts a `vmdk` file. Anyways, I have done some research and created the vdi files, but I think the last step is rearrange the partitions in the MAC OS to allow it to use the new spaces..any idea on how to do this?

**Comment by teocci** [comment]
@fengshuo211 yeah you are totally right. I remember that i did something  like that. Give me some time i will give you an answer.

**Comment by sfandrew** [comment]
Has anyone tried to use [Ruby Motion](http://www.rubymotion.com/) to deploy iOS/Android app from a ruby app? Hit a couple roadblocks due to Xcode version.

**Comment by teocci** [comment]
try to update the xcode~!

**Comment by sfandrew** [comment]
@teocci I tried but during the update process it kind of hangs up

**Comment by teocci** [comment]
mhm Don't update it directly from the App Store. Download the updated
version manually and run the update.

*Jorge Frisancho*
*Programmer & Web App Developer*
*99 Daehak-Ro, Yuseong-Gu, Daejeon, 305-764, South Korea*
*Mobile Phone :  +82-10-6589-0520* *E-mail **:** jrfdeft@gmail.com
<jrfdeft@gmail.com>*
*URL : http://eslab.cnu.ac.kr/ <http://eslab.cnu.ac.kr/>*

**Comment by teocci** [comment]
@sfandrew mhm Don't update it directly from the App Store. Download the updated
version manually and run the update.

Also you can use the command line
* `softwareupdate --list` see the list of outdated software.
* `softwareupdate --install --all `update all outdated software.
* `softwareupdate --install <product name>` update the software you named

**Comment by teocci** [comment]
Don't forge to update the command line tools  OS also

**Comment by AndrewDryga** [comment]
Hey guys, new box with latest MacOS and XCode is ready 👍. Thanks to all of you for support and suggestions.
